#!/bin/sh
##################################################################################################################
#Coupled test case 1: heat conduction in 2 spheres without collison
#copyright: Forgber, IPPT, Graz University of Technology
#BC: convective flux to the enviroment, 300/400K

cd ${0%/*} || exit 1    # run from this directory

##########################################################
#Run PaScal and cut importent data
#mpirun -np 1 PaScal < in.file_convective 
liggghts < in.liggghts

cd pascal/

octave plotMe.m
evince plot.eps







